# Generated by Django 5.1.4 on 2025-01-08 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='emblem',
        ),
        migrations.RemoveField(
            model_name='school',
            name='postal_address',
        ),
        migrations.RemoveField(
            model_name='school',
            name='schooladdress',
        ),
        migrations.RemoveField(
            model_name='school',
            name='schoolemail',
        ),
        migrations.RemoveField(
            model_name='school',
            name='slogan',
        ),
        migrations.RemoveField(
            model_name='school',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='school',
            name='username',
        ),
        migrations.RemoveField(
            model_name='school',
            name='website',
        ),
    ]
