# Generated by Django 5.1.4 on 2025-01-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_school_emblem_remove_school_postal_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='emblem',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/schoolprofile/'),
        ),
        migrations.AddField(
            model_name='school',
            name='postal_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='schooladdress',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='schoolemail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='slogan',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='telephone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='username',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
