# Generated by Django 5.1.4 on 2025-01-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_school_emblem_school_postal_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='username',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
