# Generated by Django 5.1.4 on 2025-01-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_school_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='username',
            field=models.CharField(max_length=250),
        ),
    ]
