# Generated by Django 5.1.4 on 2025-01-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_school_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Eei_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='circuit',
            field=models.CharField(choices=[('Soutpansberg East', 'Soutpansberg East Circuit')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='curriculum',
            field=models.CharField(blank=True, choices=[('CAPS', 'CAPS curriculum'), ('Cambridge', 'Cambridge curriculum')], max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='district',
            field=models.CharField(choices=[('Alfred Nzo District', 'Alfred Nzo District')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='emis_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='examination_centre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='examination_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='grade_levels',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='history',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='image1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/schoolprofile/'),
        ),
        migrations.AddField(
            model_name='school',
            name='local_municipality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='mission',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='name_of_principal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='number_of_teachers',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='persal_component_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='persal_paypoint_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='provinc',
            field=models.CharField(choices=[('Limpopo', 'Limpopo'), ('Free State', 'Free State'), ('Gauteng', 'Gauteng'), ('North West', 'North West'), ('KwaZulu-Natal', 'KwaZulu-Natal'), ('Mpumalanga', 'Mpumalanga'), ('Eastern Cape', 'Eastern Cape'), ('Northern Cape', 'Northern Cape'), ('Western Cape', 'Western Cape')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='quintile_Level',
            field=models.CharField(blank=True, choices=[('Quintile 1', 'Q1'), ('Quintile 2', 'Q2'), ('Quintile 3', 'Q3'), ('Quintile 4', 'Q4'), ('Quintile 5', 'Q5')], max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='school_fees',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='schoolname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='section_21',
            field=models.CharField(blank=True, choices=[('Section 21 (Self Reliant)', 'Self Reliant: Yes'), ('Section 21 (Self Reliant)', 'Self Reliant: No')], max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='umalusi',
            field=models.CharField(blank=True, choices=[('DBE', 'The Department of Basic Education (DBE)'), ('IEB', 'The Independent Examination Board (IEB)'), ('SACAI', 'The South African Comprehensive Assessment Institute (SACAI)')], max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='urban_rural',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='ward_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
